version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    steps:
      - checkout
      - run: ruby --version
#      - run:
#          name: Force Bundler Version
#          command: |
#            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
#            source $BASH_ENV
#            gem install bundler
      - run: ruby user_test.rb
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker build -t poc/$IMAGE_NAME
             echo $DOCKER_PWD | docker login -user_test $DOCKER_LOGIN --password-stdin
             docker push ideaslocas/$IMAGE_NAME:$TAG
#       Step 4: Docker build
#      - run:
#         name: Build and Push Docker
#          command:
#           source venv/bin/activate
#            docker build -t poc/$IMAGE_NAME:$TAG .
#            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
#            docker push ideaslocas/$IMAGE_NAME:$TAG 
