version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Test
          command:cmd |
            user_test.py
