name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run:  apt install -r requirements.txt
#    - name: run dependencies
#      run:  flake8 --exclude=venv* --statistics
    - name: run tests
      run: ruby user_test.rb    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
